local_path: '/home/localuser/Saves'
ip_address: "192.168.0.2"
name: "distantuser"
passw: "root"
remote_path: '/home/distantuser/Saves'
save_path:
  - '/var/www/html'
  - '/var/www/backupsql'
bdd: "wordpress"
bdd_user: "wordpressuser"
bdd_pass: "toto"
bdd_path_to_save: '/var/www/backupsql/'
bdd_save_name: 'dump.sql' 
